#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

use App\CommissionTask\Command\CalculateCommissionsFromFile;
use Symfony\Component\Console;

$console = new Console\Application('Commission Task', '1.0');

$console->add(new CalculateCommissionsFromFile());

$console->run();
