#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

use Symfony\Component\Console;

$console = new Console\Application('Commission Task', '1.0');

$console->add(new \App\CommissionTask\Commands\CalculateCommissionsFromFile());

$console->run();
